environment:
  matrix:
    - nodejs_version: 4
    - nodejs_version: 5
    - nodejs_version: 6
    - nodejs_version: 7
    - nodejs_version: 8
  COVERALLS_REPO_TOKEN:
    secure: 7th6RqogfpLCzC5ESW3cL7y0xvEzdR4sI8KYn6skykZdWEdSDxp0ADslyfMy3jw5

version: "{build}"

build: off

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
  - npm run coveralls
